server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: guokang@2022
    url: jdbc:mysql://10.10.1.174:3306/financial_data?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
mybatis-plus:
  type-aliases-package: com.zx.entity
  mapper-locations: mapper/*.xml
  configuration:
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #???????????? mybatis????????mp?????