server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhangxin
    url: jdbc:mysql://43.138.153.143:4306/zhangxin?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 100MB
mybatis-plus:
  type-aliases-package: com.zx.entity
  mapper-locations: mapper/*.xml
#  configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #???????????? mybatis????????mp?????