# 应用名称
spring:
  application:
    name: study
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672
  redis:
    host: 192.168.202.128
    password: 123456
    port: 6379

# 应用服务 WEB 访问端口
server:
  port: 8080


