#datasource
spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/lagou1?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: root
        password: 123456
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/lagou2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: root
        password: 123456
    sharding:
      tables:
        position:
          database-strategy:
            inline:
              sharding-column: id
              algorithm-expression: ds$->{id % 2}
          key-generator:
            column: id
            type: SNOWFLAKE
        position_detail:
          database-strategy :
            inline:
              sharding-column: pid
              algorithm-expression: ds$->{pid % 2}
          key-generator:
            column: id
            type: SNOWFLAKE
#sharding-database

