#datasource
spring:
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/lagou1?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: root
        password: 123456
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/lagou2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: root
        password: 123456
    masterslave:
      name: datasource
      master-data-source-name: master
      slave-data-source-names: slave
      load-balance-algorithm-type: ROUND_ROBIN
    sharding:
      tables:
        city:
          key-generator:
            column: id
            type: SNOWFLAKE
 #     broadcast-tables: city

#sharding-database

