



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations:
    - classpath*:/mapper/*.xml
spring:
  shardingsphere:
    props:
        sql:
          show: true
  profiles:
    active: sharding-database
